# ROS 2 Humble - Nav2 configuration for your Jetson Rover
# Footprint: 469mm x 280mm  (rectangle)
# Frames: map -> odom -> base_link
# Topics: /scan (RPLidar), /cmd_vel (driver), /tf provided by EKF + SLAM

amcl:
  ros__parameters:
    use_map_topic: true
    scan_topic: scan
    min_particles: 500
    max_particles: 2000
    update_min_d: 0.05
    update_min_a: 0.05
    kld_err: 0.02
    kld_z: 0.99
    resample_interval: 1
    transform_tolerance: 0.5
    laser_max_range: 12.0
    laser_min_range: 0.12
    laser_likelihood_max_dist: 2.0
    odom_frame_id: odom
    base_frame_id: base_link
    global_frame_id: map
    use_tf_scan_transformation: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.1

bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_bt_xml_filename: "package://nav2_bt_navigator/behavior_trees/navigate_w_replanning_and_recovery.xml"
    transform_tolerance: 0.2
    goal_reached_tol: 0.05
    plugin_lib_names:
      - nav2_back_up_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_distance_traveled_condition_bt_node
      - nav2_rate_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_remove_passed_goals_action_bt_node

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 30.0
    min_x_velocity_threshold: 0.02
    min_theta_velocity_threshold: 0.02
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["simple_goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.10
      movement_time_allowance: 10.0

    simple_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.08
      yaw_goal_tolerance: 0.15
      stateful: true

    # Use Regulated Pure Pursuit (simpler & robust)
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.6           # cruise
      max_linear_accel: 1.5
      max_angular_accel: 3.0
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.8
      lookahead_time: 0.8
      rotate_to_heading_angular_vel: 1.0
      allow_reversing: false
      use_interpolation: true
      transform_tolerance: 0.2
      use_velocity_scaled_lookahead_dist: true
      min_approach_linear_velocity: 0.1
      use_collision_detection: true
      max_allowed_time_to_collision_up_to_carrot: 1.0
      use_rotate_to_heading: true
      rotate_to_heading_min_angle: 0.785
      regulate_linear_velocity: true
      max_linear_velocity: 0.8          # match your driver cap
      max_angular_velocity: 1.6
      # Keep turns strong enough for your motors (avoid too-low duty)
      min_linear_velocity: 0.12

planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlanner2D"
      use_astar: true
      tolerance: 0.125
      downsample_costmap: false
      allow_unknown: true
      max_iterations: 400000
      max_on_approach_iterations: 10000
      minimum_turning_radius: 0.0
      motion_model_for_search: "MOORE"
      cost_travel_multiplier: 2.0
      smooth_path: true

behavior_server:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    transform_tolerance: 0.2
    use_sim_time: false
    cycle_frequency: 10.0
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["simple_goal_checker"]
    spin_plugin: "spin"
    backup_plugin: "backup"
    wait_plugin: "wait"

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.10
      movement_time_allowance: 10.0

    simple_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.08
      yaw_goal_tolerance: 0.15
      stateful: true

    spin:
      plugin: "nav2_behavior_server::Spin"
    backup:
      plugin: "nav2_behavior_server::BackUp"
    wait:
      plugin: "nav2_behavior_server::Wait"

smoother_server:
  ros__parameters:
    use_sim_time: false
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: true

waypoint_follower:
  ros__parameters:
    use_sim_time: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: true
      waypoint_pause_duration: 0.0

# ===================== Costmaps (footprint + sensors) =====================

global_costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    use_sim_time: false
    update_frequency: 2.0
    publish_frequency: 1.0
    resolution: 0.05
    track_unknown_space: true
    rolling_window: false
    width: 50
    height: 50

    footprint: [[0.2345, 0.14], [0.2345, -0.14], [-0.2345, -0.14], [-0.2345, 0.14]]
    footprint_padding: 0.03

    plugins: ["obstacle_layer", "inflation_layer"]

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: lidar
      lidar:
        topic: /scan
        sensor_frame: laser
        clearing: true
        marking: true
        max_obstacle_height: 1.0
        min_obstacle_height: 0.0
        obstacle_max_range: 10.0
        obstacle_min_range: 0.05
        raytrace_max_range: 12.0
        raytrace_min_range: 0.05

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.60
      cost_scaling_factor: 3.0

local_costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    use_sim_time: false
    update_frequency: 10.0
    publish_frequency: 5.0
    rolling_window: true
    width: 6.0
    height: 6.0
    resolution: 0.05

    footprint: [[0.2345, 0.14], [0.2345, -0.14], [-0.2345, -0.14], [-0.2345, 0.14]]
    footprint_padding: 0.03

    plugins: ["obstacle_layer", "inflation_layer"]

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: lidar
      lidar:
        topic: /scan
        sensor_frame: laser
        clearing: true
        marking: true
        max_obstacle_height: 1.0
        min_obstacle_height: 0.0
        obstacle_max_range: 8.0
        obstacle_min_range: 0.05
        raytrace_max_range: 9.0
        raytrace_min_range: 0.05

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.55
      cost_scaling_factor: 3.0

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: ""   # set if using a saved map

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: false

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: false

smoother_server_rclcpp_node:
  ros__parameters:
    use_sim_time: false

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: false

waypoint_follower_rclcpp_node:
  ros__parameters:
    use_sim_time: false
