ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # IMU orientation + yaw rate
    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  false, false, false]
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true
    imu0_queue_size: 50

    # Primary twist source. Overridden in launch to /imu_odom when encoders are offline.
    twist0: /wheel_twist
    twist0_config: [true,  false, false,   # vx, vy, vz
                    false, false, true]    # vroll, vpitch, vyaw
    twist0_queue_size: 50
    twist0_nodelay: true
    twist0_differential: false

