ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.2
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # -------------- wheel odom: x, y, vx only --------------
    odom0: wheel_odom
    #        x     y     z    roll pitch yaw   vx    vy    vz   vroll vpitch vyaw  ax   ay   az
    odom0_config: [true, true, false,
                   false, false, false,
                   true, false, false,
                   false, false, false,
                   false, false, false]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

    # -------------- IMU (from imu_filter_madgwick) : yaw + yaw rate only --------------
    imu0: imu/data
    #        x     y     z    roll pitch yaw   vx    vy    vz   vroll vpitch vyaw  ax   ay   az
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  false, false, false]
    imu0_queue_size: 10
    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: true
