ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.2
    two_d_mode: true

    transform_time_offset: 0.0
    transform_timeout: 0.2
    print_diagnostics: true
    debug: false

    # All three must be unique
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link

    # EKF will publish odom -> base_link (world is odom)
    world_frame: odom
    publish_tf: true

    # Only wheel odom fused
    odom0: wheel_odom
    odom0_config: [
      true,  true,  false,  # x, y, z
      false, false, true,   # roll, pitch, yaw
      true,  false, false,  # vx, vy, vz
      false, false, true,   # vroll, vpitch, vyaw
      false, false, false   # ax, ay, az
    ]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false
