slam_toolbox:
  ros__parameters:
    mode: mapping
    scan_topic: /scan
    map_frame: map
    base_frame: base_link
    odom_frame: odom

    provide_odom_frame: false    # EKF publishes odom->base_link
    publish_tf: true             # SLAM publishes map->odom
    use_odometry: false           # use TF (odom->base_link) as initial guess
    use_scan_matching: true

    laser_min_range: 0.2
    laser_max_range: 12.0

    minimum_travel_distance: 0.03
    minimum_travel_rotation: 0.04
    minimum_time_interval: 0.05
    resolution: 0.05
    map_publish_period: 0.2
    transform_publish_period: 0.05
    queue_size: 500

    # New parameters to improve map quality and prevent overlap
    solver_plugin: "solver_plugins::CeresSolver"

    # Scan Matcher Parameters
    scan_matcher_params:
      ceres_scan_matcher:
        use_nonmonotonic_steps: true
        max_num_iterations: 20
        num_threads: 1
      translation_weight: 10.0
      rotation_weight: 40.0

    # Map Update Parameters
    map_update_rate: 5.0
    map_update_distance_thresh: 0.4
    map_update_angle_thresh: 0.9

    # Loop Closure Parameters
    loop_closure_minimum_scan_period: 0.5
    loop_closure_search_radius: 5.0

    # Correlation parameters
    correlation_search_space_dimension: 0.2
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1