slam_toolbox:
  ros__parameters:
    mode: mapping
    scan_topic: /scan
    map_frame: map
    base_frame: base_link
    odom_frame: odom

    provide_odom_frame: true    # EKF publishes odom->base_link
    publish_tf: true             # SLAM publishes map->odom

    # For now: NO odom in SLAM, just scan matching
    use_odometry: false
    use_scan_matching: true

    # Correct RPLidar limits + no throttling
    minimum_laser_range: 0.2     # meters
    maximum_laser_range: 12.0    # meters
    throttle_scans: 1            # use every scan

    minimum_travel_distance: 0.03
    minimum_travel_rotation: 0.04
    minimum_time_interval: 0.05
    resolution: 0.05
    map_publish_period: 0.2
    transform_publish_period: 0.05
    queue_size: 500
