slam_toolbox:
  ros__parameters:
    mode: mapping
    scan_topic: /scan
    map_frame: map
    base_frame: base_link
    odom_frame: odom

    provide_odom_frame: true     # SLAM publishes map->odom
    publish_tf: true             # enable TF from SLAM
    use_odometry: true
    odom_topic: /odometry/filtered   # <— point to EKF topic

    minimum_travel_distance: 0.03
    minimum_travel_rotation: 0.04
    minimum_time_interval: 0.05
    resolution: 0.05
    map_publish_period: 0.2
    transform_publish_period: 0.05
    queue_size: 500
